# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: Gerbera
version: "0.1.0"
slug: gerbera
description: Gerbera UPNP/DLNA server
url: "https://github.com/opulentrich/homeassistant-addons/tree/main/gerbera"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
  - media:r
image: "ghcr.io/opulentrich/{arch}-addon-gerbera"
ports:
  49152/tcp: 49152
