# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: G-Homa2MQTT
version: "0.1.9"
slug: ghoma2mqtt
description: Bridge to connect G-Homa plugs to HomeAssistant via MQTT
url: "https://github.com/opulentrich/ghoma2mqtt/tree/main/ghoma2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/opulentrich/{arch}-addon-ghoma2mqtt"
ports:
  4196/tcp: 4196
services:
  - mqtt:need
