# https://developers.home-assistant.io/docs/add-ons/configuration#add-on-config
name: ghoma2mqtt add-on
version: "0.1.1"
slug: ghome2mqtt
description: ghoma2mqtt add-on
url: "https://github.com/opulentrich/ghoma2mqtt/tree/main/ghoma2mqtt"
arch:
  - armhf
  - armv7
  - aarch64
  - amd64
  - i386
init: false
map:
  - share:rw
options:
  message: "Hello world..."
schema:
  message: "str?"
image: "ghcr.io/opulentrich/{arch}-addon-ghoma2mqtt"
ports:
  4196/tcp: 4196
services:
  - mqtt:need
